export default function Billing() {
  return (
    <article>
      <h1 className="text-3xl font-bold mb-4">
        Billing & Usage
      </h1>

      <p className="text-gray-300 mb-6">
        Axeiro uses simple, transparent billing. You pay a platform subscription
        fee and the actual cloud usage generated by your deployments.
      </p>

      <h2 className="text-xl font-semibold mt-10 mb-3">
        1. Platform Subscription
      </h2>
      <p className="text-gray-400 mb-4">
        Axeiro is a paid platform from day one. Your subscription plan defines
        limits such as the number of deployments, redeployments, and available
        features.
      </p>

      <h2 className="text-xl font-semibold mt-10 mb-3">
        2. Cloud Usage Costs
      </h2>
      <p className="text-gray-400 mb-4">
        Applications deployed through Axeiro run on managed cloud infrastructure.
        Cloud costs are calculated based on resource usage and are tracked using
        cost allocation tags.
      </p>

      <p className="text-gray-400 mb-4">
        Usage data may not be real-time and can take time to appear due to cloud
        provider reporting delays.
      </p>

      <h2 className="text-xl font-semibold mt-10 mb-3">
        3. Invoices & Payments
      </h2>
      <p className="text-gray-400 mb-4">
        You can view and download invoices from the dashboard. Invoices include
        the Axeiro platform fee and any applicable cloud usage charges.
      </p>

      <h2 className="text-xl font-semibold mt-10 mb-3">
        4. Usage Visibility & Limits
      </h2>
      <p className="text-gray-400 mb-4">
        Axeiro provides usage summaries and spend indicators to help you stay
        within budget. Soft limits and warnings may be applied, but deployments
        are not automatically blocked unless explicitly configured.
      </p>

      <div className="mt-10 border-t border-white/10 pt-6 text-sm text-gray-400">
        Back to →{" "}
        <a
          href="/docs/getting-started"
          className="text-[#c900ff] hover:underline"
        >
          Getting Started
        </a>
      </div>
    </article>
  );
}
